export enum WhatsAppCampaignEventType {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  SNAPSHOT_GENERATED = 'SNAPSHOT_GENERATED',
  RECIPIENTS_GENERATED = 'RECIPIENTS_GENERATED',
  SCHEDULED = 'SCHEDULED',
  DISPATCHED = 'DISPATCHED',
  DISPATCH_STARTED = 'DISPATCH_STARTED',
  DISPATCH_COMPLETED = 'DISPATCH_COMPLETED',
  DISPATCH_FAILED = 'DISPATCH_FAILED',
  CANCELLED = 'CANCELLED',
  LEGACY_STATUS_MIGRATED = 'LEGACY_STATUS_MIGRATED',
}

export enum WhatsAppAudienceSourceType {
  LIST = 'LIST',
  SEGMENT = 'SEGMENT',
}
